### ISSUE TITLE
Merge with GRUB2?

### ISSUE THREAD

**Issue by ghost** [johnlane/grub#1]
There is some nice work here and I can really see the benefit of these additions.

Are there any plans to merge your changes upstream to GRUB2?

**Comment by johnlane** [comment]
Hi, I have submitted the work upstream. I have taken feedback and made some changes. I have resubmitted patches on 29th June (http://lists.gnu.org/archive/html/grub-devel/2015-06/msg00109.html). I have as yet had no response to that posting. I should chase them up...

**Comment by johnlane** [comment]
Just to let you know that I have chased upstream about getting this work adopted but I haven't got anywhere with it. I have responded to feedback but they haven't responded to let me know what's preventing its adoption. I'll update this tread with any updates.

If anyone else wants to add their support to this they could reply to the above-linked thread on the mailing list to show support.

**Comment by johnlane** [comment]
General update for anyone interested. I have merged upstream into this repo today. The crypto-patches are still not in upstream, however. The patches on the website are compatible with upstream commit abf9beb7.

**Comment by desmond-decker** [comment]
You are my goddamned hero, buddy. This should be in the upstream!

**Comment by johnlane** [comment]
Just an update for anyone interested. Upstream changed the status on the issues:
- http://savannah.gnu.org/bugs/?43731 Priority: 5 - Normal => 3 - Low
- http://savannah.gnu.org/bugs/?43727 Priority: 5 - Normal => 3 - Low

So nothing exciting to report :)

**Comment by neuhaus** [comment]
Ubuntu 16.04 comes with `/usr/lib/grub/i386-pc/cryptodisk.mod` as part of the `grub-pc-bin` package.

**Comment by johnlane** [comment]
@neuhaus that's the stock `cryptodisk` surely? Or are you saying that it includes these patches? What does `cryptomount -h` show (compare with [this](http://grub.johnlane.ie/assets/grub-crypto.png)) ?

**Comment by neuhaus** [comment]
Oh, you're right. Sorry for the confusion.
(I don't use cryptodisk in grub so I can't tell you what the output is, sorry)

**Comment by awnumar** [comment]
1+ for this. If merged, we'd have the ability to create drives with truly deniable encryption.

**Comment by johnlane** [comment]
Grub Crypto is currently being discussed on [help-grub](http://lists.gnu.org/archive/html/help-grub/2017-02/msg00017.html) in case anyone wishes to join in...

**Comment by xenithorb** [comment]
I would like to see this rekindled if at all possible. I recently merged the patches you provided with the official fedora packaged version of grub here on my COPR repo: https://copr.fedorainfracloud.org/coprs/xenithorb/grub2-crypto-enhance/ (as an experiment, it's not well tested.) 

Thanks for your improvements! It's certainly in the right direction, and I hope you can get upstream on board soon.

**Comment by johnlane** [comment]
I've just merged this repo too, to upstream master `afd0e534`.

**Comment by johnlane** [comment]
I have updated the patches in line with the current master branch and resubmitted them to the grub-devel mailing list.

**Comment by amoghe** [comment]
Since this has not been merged upstream yet :

IIUC all the changes in this repo only target the `cryptodisk` module, so I should be able to build this repo, and simply take that module and drop it onto my current system, correct? Any reasons this would not work?

**Comment by johnlane** [comment]
@amoghe, the modules affected by this work are `cryptodisk` and `luks`. I think that you should be able to do what you suggest as long as the build and run-time versions are the same. But I have not tried to do this myself.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
