### ISSUE TITLE
Remotely unlocking LUKS partitions, grub gets in the way

### ISSUE THREAD

**Issue by neuhaus** [johnlane/grub#10]
Hello,

I have a server with an encrypted root partition that I want to unlock by logging in via dropbear running in the initrd image.

It appears that grub gets in the way, if it detects the LUKS partition a line "cryptomount -u <uuid>" is automatically added to the grub configuration. What's the best way to tell grub not to deal with LUKS partitions?

**Comment by johnlane** [comment]
You could manually edit the `grub.cfg`, which I expect is being generated by `grub-mkconfig`. These extensions don't apply to auto-generated grub configs so this is probably off-topic here...

**Comment by neuhaus** [comment]
I overlooked the simple solution of setting `GRUB_ENABLE_CRYPTODISK=n` in `/etc/default/grub`.
