### ISSUE TITLE
Support for IV skip parameter

### ISSUE THREAD

**Issue by ghost** [johnlane/grub#12]
According to cryptsetup man page plain in order to decrypt plain dm-crypt partition following parameters are needed: password, hash, cipher, key size, partition start offset and IV skip parameter. Currently there is no support for last option. It is missing both in source code and in cryptomount help page.

Repeating from man page:

--skip, -p how many sectors of the encrypted data to skip at the beginning. This is different from the --offset options with respect to IV calculations. Using --offset will shift the IV calculation by the same negative amount. Hence, if --offset n, sector n will be the first sector on the mapping with IV 0. Using --skip would have resulted in sector n being the first sector also, but with IV n. This option is only relevant for create action.

**Comment by johnlane** [comment]
I took a *very quick* look at this for you this evening.

Adding the parameter would be easy but implementing the functionality would require modifying function `grub_cryptodisk_create` (it's wholly defined in patch 4). I only moved that function from one file (`luks.c`) to another (`cryptodisk.c`) - I never messed with its implementation and I don't understand its internals.

I'd be concerned that if I started tinkering around in there then it might further jepoardise chances of getting the work adopted upstream.

That said, I will see if I can work it out. Or you could do the same and submit me a pull request. Would that be something you could do ?

I am busy on other things though so it'll have to be as-and-when I can fit it in.

**Comment by ghost** [comment]
I am interesting in supporting this parameter for the purpose of plausible deniability, because this option is not required, I am not interested in it as much.

I agree that modifyng more code decreases chances of adopting pull in mainstream. I am inclined toward adopting pull with dm-crypt without IV. 

I have strong experience in C programming in areas of low-level programming, I am also interested in areas of booting. I think I could do it, but it is unlikely given that the feature is not really required.

**Comment by johnlane** [comment]
Closing because the OP user was deleted.
