### ISSUE TITLE
Grub scripts for generated configurations?

### ISSUE THREAD

**Issue by xenithorb** [johnlane/grub#13]
Assuming the rest of this goes forward and gets merge into grub, what will be the plan to allow end users like myself to configure it?

The biggest issue that I see is most distributions upgrade kernels during the normal upgrade process that usually triggers some script like grubby (which in turn calls `grub-mkconfig`) to regenerate the configuration.  This is of course why we have `/etc/grub.d/` and `/etc/default/grub` 

As it doesn't seem like there's currently anything in place to handle this with these patches, I wanted to start a discussion to talk about my use case:

How would I, through `/etc/default/grub` and or `/etc/grub.d` ensure that when `grub-mkconfig` is run, I retain my configuration of 

```
cryptomount -k (hd0,1)/keyfile -O 30 -S 50 hd1,1
```
(yes taken from the examples)

Right now it would seem the current scripts do a fine job of including `insmod luks` and `insmod cryptodisk` by simply adding `GRUB_CRYPTODISK=y` to `/etc/default/grub`. This also results in an entry right before the kernel load 

```
cryptomount -u <UUID>
```

I would propose that perhaps that is extrapolated to include 

```
GRUB_CRYPTODISK_KEY
GRUB_CRYPTODISK_KEY_OFFSET
GRUB_CRYPTODISK_KEY_SIZE
GRUB_CRYPTODISK_HEADER
GRUB_CRYPTODISK_PLAIN
```

**Comment by johnlane** [comment]
I have not addressed the problem of autogenerating config. I hope we can get the functionality provided thus far into the main Grub so those that wish to may rool up their sleeves and edit their `grub.cfg` to their needs.

There are issues to overcome for autogeneration, not least a reliable way to identify headerless devices.

I do think a plan for autogeneration is needed and this is a good place to collate peoples' thoughts on the subject.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
