### ISSUE TITLE
Installation problem with only grub-crypto

### ISSUE THREAD

**Issue by StevenDoesStuffs** [johnlane/grub#17]
When running `grub-probe -d /dev/SysVG/root` I get an error of `cannot seek /dev/mapper/cryptroot`.
When running `grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB` I got an error of 
```
info: /dev/mapper/cryptboot is not present
into: drive = -1
error: disk 'cryptouuid/bd52c91.....' not found.
```

I'm trying to set up LVM on LUKS, with a detached header on the boot partition, and my lsblk looks like so:
```
NAME               SIZE MOUNTPOINT UUID
loop0              495M            
sda               29.8G            
├─sda1              16G            813dda54-94f4-4ce9-b460-f3ea46107085
└─sda2            13.8G            5b4eec345b4eec21
sdb               14.9G            2019-05-01-05-36-16-00
├─sdb1             608M            2019-05-01-05-36-16-00
└─sdb2              64M            02A2-79A6
nvme0n1            477G            
├─nvme0n1p1        450M            282AB6642AB62EA6
├─nvme0n1p2        100M /boot/efi   DEB6-873C
├─nvme0n1p3         16M            
├─nvme0n1p4      233.8G            
├─nvme0n1p5        512M            5ec4a3af-3894-4935-9cf5-08cee5cd8bc2
│ └─cryptboot      496M /boot      fb3b27c1-5824-45cc-86e9-b4c93db9f6f8
└─nvme0n1p6      242.1G            528f6424-2cf5-479d-a75d-736845573dc8
  └─cryptroot    242.1G            2M9dSh-s0Uj-2UAl-Emvh-JEfF-BdHW-3sKS2e
    ├─SysVG-swap    24G            d8e713d9-00bf-4852-8df8-654ee47dedc3
    └─SysVG-root 218.1G /          941f9bac-66ca-41d1-a82b-a3eafda60d2d
```
Notice that there is nothing with UUID `bd52c91...`.
I am using the grub-luks-keyfile package from the AUR, and grub-install and grub-mkconfig (grub-probe) work using regular grub.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
