### ISSUE TITLE
PARTUUID

### ISSUE THREAD

**Issue by reagentoo** [johnlane/grub#22]
My usage pattern involves at least two drives. The first drive has a grub installed, grub.cfg, luks header and a key. On the second drive, there is only one partition with a cryptodisk without any headers.
Grub currently does not able to identify the drive by PARTUUID. Any workaround may be?

**Comment by reagentoo** [comment]
Good news. A year ago this was introduced to `probe` command:
https://git.savannah.gnu.org/cgit/grub.git/patch/?id=f2b9083f859c7dbf44a7a8e96ee0cf202f9a4187
https://git.savannah.gnu.org/cgit/grub.git/patch/?id=c7cb11b2198a07098143ecc67b19497ba25df28f

Usage:
`probe --part-uuid device`

**Comment by reagentoo** [comment]
I've added a  `--part-uuid` for `search` command:
https://github.com/reagentoo/grub/commit/44ce0140759d26144fd07f6af62aea284565e498
[search_partuuid](https://github.com/reagentoo/grub/tree/search_partuuid) branch

Opened bugs:
https://savannah.gnu.org/bugs/index.php?59407

@johnlane Could you please share your experience on how to push changes upstream?

**Comment by johnlane** [comment]
Hi, sorry not been active on this recently. I did have some back-and-forth with patches but it was too difficult for me to make any progress - I don't have the time to devote to this personally. I think somebody else was pushing my patches again to see if some traction could be gained. But I'm sorry that I haven't had any time to devote to this in recent times.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
