### ISSUE TITLE
is it possible to have a non US keymap?

### ISSUE THREAD

**Issue by j75** [johnlane/grub#26]
I cannot find any information about how to change the default keyboard layout to another one (in my case French AZERTY) to be able to edit the command at the initial prompt.

There is a command named **keymap** which, if I type a bad value, sais `error: file /boot/grub/layouts/french.gkb not found` - where could I find this file? Where could I find more details about the **keymap** command?

At [The list of command-line and menu entry commands](https://www.gnu.org/software/grub/manual/grub/grub.html#Command_002dline-and-menu-entry-commands) there's no description of **keymap**, only of **keystatus**!

**Comment by johnlane** [comment]
This is a question that should be directed upstream, it isn't specific to the extensions provided here.
