### ISSUE TITLE
Luks with detached header

### ISSUE THREAD

**Issue by piec** [johnlane/grub#3]
Hi, nice work !

I'm trying to use a luks partition with detached header, the partition is btrfs over dm-crypt.
(I also have a setup with btrfs over classic classic luks so I guess it should be fine).
My grub is located on an unencrypted partition right now to simplify things.

```
cryptsetup luksDump .../header
[...]
Version:        1
Cipher name:    xxx
Cipher mode:    yyy
Hash spec:      zzz
Payload offset: 0

UUID:           735.....64600
[...]
```

My setup looks like this:

```
insmod luks
insmod gcry_rijndael
insmod gcry_sha512
insmod btrfs
cryptomount -H (hd1,gpt2)/header (hd0,gpt4)
set root='cryptouuid/735.....64600'
```

cryptomount asks for the passphrase and apparently correctly opens with slot 0
but then if I try to `ls /` I get `disk `cryptouuid/735.....64600' not found.`
Also `ls (crypto0)` gives `error: disk `crypto0' not found.`

I tried with and without hypens in the `set root`.
Am I doing something wrong ?

---

Head revision (efba8c1), built using the AUR [grub-git](https://aur4.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=grub-git) package, just replacing the git url

**Comment by johnlane** [comment]
Omit the parentheses on the cryptsetup drivespec:

```
cryptomount -H (hd1,gpt2)/header hd0,gpt4
```

You should then be able to do
```
ls (cryptouuid/735.....64600)
```

**Comment by piec** [comment]
Yay ! it works now :)
With a tweaked initramfs obviously. Archlinux encrypt hook doesn't support the '--header' parameter yet. I might contribute that to them.

**Comment by johnlane** [comment]
That's [already](https://bugs.archlinux.org/task/42851?only_watched=1&type%5B0%5D=&sev%5B0%5D=&due%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&reported%5B0%5D=) raised that them Piec. If you use systemd in the initramfs then you can achieve what you want using unit files. That;s the approach that I took after having difficulties unlocking an LVM volume group. See [this thread](https://bbs.archlinux.org/viewtopic.php?id=191132), [this post](https://bbs.archlinux.org/viewtopic.php?pid=1479994#p1479994) and bug reports [42851](https://bugs.archlinux.org/task/42851) and [43054](https://bugs.archlinux.org/task/43054).

**Comment by piec** [comment]
Cool ! I didn't know about it thanks
