### ISSUE TITLE
Booting live iso files from encrypted partition

### ISSUE THREAD

**Issue by smacz42** [johnlane/grub#5]
As explained [here](http://ms26ilrtla2rfuzz.onion.link/) I am attempting to boot a live iso that resides in an encrypted partition. However:

> But actually it doesn't work because the live scripts can't find the iso image right now by just mounting the encrypted partition (cryptsetup luksOpen etc.). So it will give you strange errors because it doesn't handle the mapping between filesystem and kernel modules right and is not aware of dm-crypt.

Some say that this is possible by booting a kernel (stored in the unencrypted /boot) to use to boot the iso in the encrypted filesystem. Would this patch enable GRUB to map between the filesystem and the kernel modules?

Just a shot in the dark here.

**Comment by johnlane** [comment]
Hello. If I understand you correctly, you have a encrypted partition containing an iso that you would like to boot. My patches allow Grub to unlock an encrypted partition. Once that is done, its usual commands can be used to boot the iso in the same way as if that partition wasn't encrypted.

That said, note that the decryption done by Grub allows Grub to see the encrypted partition so that it can load any specified kernel, initramfs or iso. The booting operating system must also have access to the filesystems it needs and must unlock any encrypted partitions this requires. The "unlocking" state does not pass from the boot loaded (Grub) to the operating system.

The normal way for the OS (Linux) to unlock encrypted partitions is to include the necessary keys in an initramfs.

You may run into problems if the booting kernel cannot unlock the filesystems it needs. I haven't personally tried to boot an ISO that resides on an encrypted partition.

**Comment by xenoterracide** [comment]
@johnlane can you provide instructions on how to do this? I've had problems constructing the Linux line

```
#!/bin/sh$
exec tail -n +3 $0$
# This file provides an easy way to add custom menu entries.  Simply type the$
# menu entries you want to add after this comment.  Be careful not to change$
# the 'exec tail' line above.$
$
menuentry "Manjaro grub_iso"  {$
    set isofile="/boot/images/manjaro-gnome-21.0.7-minimal-210614-linux510.iso"$
    set dri="free"$
    set lang="en_US"$
    set keytable="us"$
    set timezone="America/Detroit"$
    search --no-floppy -f --set=root $isofile$
    probe -u $root --set=abc$
    set pqr="/dev/disk/by-uuid/$abc"$
    loopback loop $isofile$
    linux (loop)/boot/vmlinuz-x86_64  img_dev=$pqr img_loop=$isofile driver=$dri tz=$timezone lang=$lang keytable=$keytable copytoram$
    initrd  (loop)/boot/intel_ucode.img (loop)/boot/initramfs-5.10-x86_64.img$
}
```

```
❯ ls /boot                                                                                      # ~
efi     initramfs-5.10-x86_64-fallback.img  intel-ucode.img       memtest86+
grub    initramfs-5.10-x86_64.img           linux510-x86_64.kver  syslinux
images  install                             memdisk               vmlinuz-5.10-x86_64
❯ ls /boot/images                                                                               # ~
manjaro-gnome-21.0.7-minimal-210614-linux510.iso
```

**Comment by johnlane** [comment]
The format of the Linux line is heavily dependent on the structure of the ISO you're trying to boot. I've never tried Manjaro myself but let's assume it follows along the lines of Arch...

This is an excerpt from my own `grub.cfg`, unedited, so it's what I use myself to boot isos off the usb stick.
```
# Image device inside Linux (assumes partition label is set)
imgdevpath='/dev/disk/by-partlabel/boot'
export imgdevpath

function boot_archlinux {
        arch=$1
	shift
	y=2020
	m=12
	d=01
	a=$arch
	isofile="/iso/archlinux-${y}.${m}.${d}-${a}.iso"
	echo "Booting $isofile for $arch $*"
	loopback loop $isofile
	linux (loop)/arch/boot/$arch/vmlinuz-linux archisolabel=ARCH_${y}${m} img_dev=$imgdevpath img_loop=$isofile earlymodules=loop "$@"
	initrd (loop)/arch/boot/$arch/initramfs-linux.img
}

submenu 'Arch Linux' {
  menuentry 'Arch Linux i686'   { boot_archlinux i686 }
  menuentry 'Arch Linux i686 (no kms)'   { boot_archlinux i686 nomodeset }
  menuentry 'Arch Linux x86_64' { boot_archlinux x86_64 }
  menuentry 'Arch Linux x86_64 (no kms)' { boot_archlinux x86_64 nomodeset }
}
```
To illustrate the differences between various isos, here are other examples from the same `grub.cfg`:

```
menuentry 'Fedora Workstation 28' {
  set isofile="/iso/Fedora-Workstation-Live-x86_64-28-1.1.iso"
  loopback loop $isofile
  linux  (loop)/isolinux/vmlinuz root=live:CDLABEL=Fedora-WS-Live-28-1-1 iso-scan/filename=$isofile rd.live image
  initrd (loop)/isolinux/initrd.img
}

menuentry 'Ubuntu 18.04 Desktop' {
  set isofile="/iso/ubuntu-18.04-desktop-amd64.iso"
  loopback loop $isofile
  linux  (loop)/casper/vmlinuz file=/cdrom/preseed/ubuntu.seed boot=casper iso-scan/filename=$isofile quiet splash ---
  initrd (loop)/casper/initrd.lz
}

submenu 'Tools' {
  menuentry 'Clonezilla Live' {
    set isofile="/iso/clonezilla-live-20180329-artful-amd64.iso"
    loopback loop $isofile
    linux (loop)/live/vmlinuz boot=live live-config nolocales edd=on nomodeset ocs_live_run=\"ocs-live-general\" ocs_live_extra_param=\"\"   ocs_live_keymap=\"\" ocs_live_batch=\"no\" ocs_lang=\"\" ip=frommedia nosplash toram=filesystem.squashfs findiso=$isofile
    initrd (loop)/live/initrd.img
  }
  menuentry 'System Rescue CD' {
    set isofile="/iso/systemrescuecd-x86-4.8.3.iso"
    loopback loop $isofile
    linux (loop)/isolinux/rescue32 isoloop=$isofile nomodeset
    initrd (loop)/isolinux/initram.igz
  }
  menuentry 'Tails' {
    set isofile="/iso/tails-amd64-3.6.2.iso"
    loopback loop $isofile
    linux (loop)/live/vmlinuz fromiso=$imgdevpath/$isofile boot=live config noswap nopersistent noautologin splash
    initrd (loop)/live/initrd.img
  }
}
```
Hopefully that's of some use?

If you need to work any of this out yourself for other distros you'll need to dig into the startup code of that distro - mount the iso and try to work through what the initramfs does to boot it. It must be coded to receive parameters passed to it via the kernel command line and you need to work out what they are.

**Comment by xenoterracide** [comment]
thanks that helped me figure it out, what really made me pay attention was the longer path to the initrd for the arch initird image. For some reason I never put together that said image was on the ISO.
