### ISSUE TITLE
Plain mode cipher issue

### ISSUE THREAD

**Issue by desmond-decker** [johnlane/grub#9]
When attempting to decrypt a "plain mode" container (with -p), if the cipher is incorrectly typed the password prompt comes up but then hangs and can't decrypt or exit, and the system needs to be rebooted.

A quick check to see if the cipher inputted by the user (with -c) is correct/available (and an error an if not) before moving to the passphrase prompt would be good.

**Comment by johnlane** [comment]
Hi, if you want to submit a PR I can take a look at it, but I haven't the time to look at it myself right now...

**Comment by ChewbaccaKL** [comment]
Here is how to reproduce the thing:
Take my compiled efi-grub: with RMD160 and without:

http://users.camk.edu.pl/chris/bugs/cryptomount/with-rmd160/bootx64.efi
http://users.camk.edu.pl/chris/bugs/cryptomount/without-rmd160/bootx64.efi

when you boot from that (ensure there are no loadable modules on grub-accessible filesystem), do:

    cryptomount hd0 -p -c aes-xts-plain64

(and type whatever as a password)

In the first case, the filesystem is created (it contains garbage, but that's ok).
In the second case the grub hangs.

The only difference is compiled gcry_rmd160 in the bootx64.efi.
The cryptomount does not check whether the module exists.

**Comment by johnlane** [comment]
AH, I get what this is about now. I will take a look at it the next time I focus on this project - meanwhile if it's urgent for you and you can offer a fix please send me a pull request.

**Comment by johnlane** [comment]
Thank you for your interest in these Grub crypto extensions. Your issue here has been closed now that  [similar features have been implemented in Grub](https://gitlab.com/gnu-grub/grub/-/commit/1deb521452b288fe8256dcc7bc14228aa42b568e). Please direct your query to a [Grub mailing list](http://www.gnu.org/software/grub/grub-mailinglist.html) if your issue remains relevant.
